[package]
name = "MrRustboto"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
serenity = "*"
tokio = {version = "*", features = ["full"] }
dotenv = "*"